name: Sync WeRead to Notion

on:
  schedule:
    - cron: "0 12 * * *"  # 北京时间20:00运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # 确保 requirements.txt 存在
          if [ ! -f "requirements.txt" ]; then
            echo "创建默认 requirements.txt 文件"
            echo "requests==2.31.0" > requirements.txt
            echo "notion-client==2.4.0" >> requirements.txt
            echo "python-dotenv==1.0.0" >> requirements.txt
            echo "selenium==4.21.0" >> requirements.txt
            echo "webdriver-manager==4.0.1" >> requirements.txt
          fi
          
          pip install -r requirements.txt
          
      - name: List files (Debug)
        run: |
          echo "当前目录:"
          pwd
          echo "文件列表:"
          ls -la
          echo "requirements.txt 内容:"
          cat requirements.txt
          
      - name: Run synchronization
  env:
    WR_TOKEN: ${{ secrets.WR_TOKEN }}
    NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    DATABASE_ID: ${{ secrets.DATABASE_ID }}
    DEBUG_MODE: "true"  # 启用详细调试模式
  run: |
    # 打印环境变量验证（隐藏敏感信息）
    echo "WR_TOKEN 存在: ${#WR_TOKEN} 字符"
    echo "NOTION_TOKEN 存在: ${#NOTION_TOKEN} 字符"
    echo "DATABASE_ID: $DATABASE_ID"
    
    # 运行主程序
    python main.py
    
    # 保存调试信息
    mkdir -p logs
    echo "同步完成时间: $(date)" > logs/debug.log
